### ISSUE TITLE
Customising colours (help request - not an issue)

### ISSUE THREAD

**Issue by drk-mtr** [sainnhe/edge#1]
I really like this scheme - thanks for sharing!

I need a little more contrast, so I'm trying to make the white whiter and the background a little darker.

Are you able to advise on which shade I need to change in order to modify the background by any chance? I tried a find/replace on `#262729` but didn't get anywhere.

**Comment by sainnhe** [comment]
Edit `template/_palette_dark.colortemplate` and modify `foreground` and `background`.

Then open `template/edge.colortemplate` and execute `:Colortemplate! ./` to generate this color scheme.

**Comment by drk-mtr** [comment]
Fantastic - thanks very much for pointing me in the right direction!
