### ISSUE TITLE
termguicolors option, wrong colors?

### ISSUE THREAD

**Issue by lourdas** [sainnhe/edge#11]
Hi,

I'm using vim 8.2 with the termguicolors option enabled and alacritty 0.4.2. I have installed your theme, but when I enable termguicolors, the colors are wrong.

This is vim with termguicolors enabled:
![Screenshot_20200420_091316](https://user-images.githubusercontent.com/397916/79719578-8fcf3880-82e7-11ea-924a-973acefaa326.png)
And with termguicolors disabled:
![Screenshot_20200420_091338](https://user-images.githubusercontent.com/397916/79719599-99f13700-82e7-11ea-9a3d-c793811d27bb.png)
I think that the theme looks correctly if I have termguicolors disabled, but I'd like your opinion.

Is there something wrong with my vim setup?

**Comment by sainnhe** [comment]
I can't reproduce this, please provide minimal vimrc to reproduce the first screenshot.

**Comment by lourdas** [comment]
With this .vimrc:

    execute pathogen#infect()
    set termguicolors
    set background=light
    let g:edge_style='neon'
    let g:edge_disable_italic_comment=1
    let g:airline_themes='edge'
    colorscheme edge

Vim looks like this:
![Screenshot_20200420_150505](https://user-images.githubusercontent.com/397916/79749781-74c8ec80-8318-11ea-84dc-6118ea43cab7.png)

**Comment by sainnhe** [comment]
I still cannot reproduce this using your vimrc, everything works fine in my machine, both in vim 8.2 and neovim . And I'm also using alacritty 0.4.2, pretty sure it supports true colors.

So the only possible reason I can think of is that your vim does not support termguicolors. Check the output of this command:

```shell
$ vim --version | grep termguicolors
```

Btw, if you set/unset `termguicolors` via vim command mode, you'll need to apply this color scheme again:

```vim
:colo edge
```

**Comment by lourdas** [comment]
`vim --version | grep termguicolors` gives:

    +autochdir         +float             +multi_byte        +termguicolors

So, termguicolors is enabled. I will try with a non existing .vimrc.

**Comment by lourdas** [comment]
I believe that the Alacritty setup is somehow at fault for my distro (Gentoo). Konsole displays the color the same as in your screenshots (and with termguicolors enabled). I will investigate further with the Gentoo devs.

**Comment by wirerydr** [comment]
For what it's worth (possibly nothing), I noticed that my alacritty.yml had the following in it near the top, which was causing me colour problems:
```yml
env:
#  TERM:		xterm
```

By default, alacritty will try a `$TERM` setting of '**alacritty**' if it can find a matching termcap, and fallback to '**xterm-256color'** if it cannot.  In my case I don't have an alacritty termcap, and so having `$TERM` set to '**xterm-256color'** caused me weird color problems.  When I uncommented the alacritty config line above, forcing it to set a `$TERM` value of '**xterm**', my problem went away.  I also set it manually to '**xterm-256color**' to confirm that this `$TERM` setting caused me problems - and it did.

_TL;DR_:  Check out what your actual shell $TERM variable is getting set to by alacritty (versus Konsole), and see if perhaps fiddling with that might fix things for you.

**Comment by sainnhe** [comment]
Closed since it looks like a problem with the terminal emulator.
