### ISSUE TITLE
[Question] What are the differences between styles?

### ISSUE THREAD

**Issue by kristijanhusak** [sainnhe/edge#13]
Hi,

nice color scheme, like both dark and light version.
Can you elaborate on differences between styles?

For dark version, I see some differences in background color, but for light version, I don't see anything that's different, at least not eye catching.

I noticed that hex values are a bit different, but can't really figure them out when comparing.

Maybe adding some explanation in readme what the differences are?

Thanks!

**Comment by sainnhe** [comment]
The light variants are almost the same. If you cannot distinguish between them, you can use the default one instead.

And thanks for your notice, I've updated the README.

**Comment by kristijanhusak** [comment]
Ok, thanks.
