### ISSUE TITLE
Theme doesn't work in standard terminal or iTerm2

### ISSUE THREAD

**Issue by Integralist** [sainnhe/edge#19]
I'm trying to use this theme but it's not displaying quite correctly in either macOS terminal app or even iTerm2 (I prefer to use terminal.app but thought I'd check iTerm2 to see if the colour palette was better supported there).

<img width="1538" alt="Screenshot 2020-12-16 at 11 59 26" src="https://user-images.githubusercontent.com/180050/102346021-2a2a6d80-3f96-11eb-9467-725ead251d23.png">

I raised this same issue with another theme I wanted to try out (which appeared visually a lot more broken) and turns out the issue is with the terminal theme being used (see [details here](https://www.nordtheme.com/docs/ports/vim/installation)).

> Vim in terminal mode must be used with a Nord terminal emulator theme in order to work properly! Vim in terminal mode uses the 16 color codes provided by the terminal emulator. When used with another color theme than the one provided by one of Nord's terminal emulator ports, the colors in Vim won't use Nord's color palettes! This will result in different styles than those defined by Nord Vim and could make it appear that there is a problem with the Nord Vim theme while the actual problem are missing Nord colors.

So my question is now, what terminal theme would you recommend I use (either iTerm2 or Terminal.app, preferably the latter) to get your vim theme to work more accurately?

**Comment by sainnhe** [comment]
It's true colors problem, I provided detailed debug steps in FAQ.

https://github.com/sainnhe/edge/blob/e40571b69c78f60b6acf0e7b3f1b008b5c72778a/doc/edge.txt#L296-L318

**Comment by Integralist** [comment]
So terminal.app doesn't quite have the true color support necessary, so I switched to iTerm2 which does support true color but I still had issues with it rendering the theme.

From the 4 items listed to check, I did the first three and the last item I kinda already have by virtue of setting my colorscheme using `autocmd vimenter`.

I'll keep digging, as it looks like most of the theme is ok with the exception of the background colour being almost black instead of purple like your README shows. Which makes me think the terminal's own theme is messing something up (as per Nord's suggestion to use their own terminal theme to avoid that issue).

**Comment by bngldmn** [comment]
Hi,
It looks like I am having the same issue. I am using neovim over tmux on alacritty for mac. I have verified that the terminal supports true color, but the vim colors still appear wrong.
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/60186599/111489609-ab69db80-8710-11eb-95f3-6e896fca1374.png">
Here is what my vimrc looks like with this color scheme:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/60186599/111489754-cb999a80-8710-11eb-8f0e-d25ff6c3d8a9.png">
Most of the colors look ok, except for the comments, where the background and foreground colors seem to be switched.
Here is my tmux.conf:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/60186599/111490112-1e735200-8711-11eb-9865-f0ca64678d1e.png">
It also looks like the sonokai colorscheme is having a similar problem, where certain highlight groups have the foreground and backgronud colors switched.
Also, when I load files with macvim, or on neovim (with terminal) without tmux, the colors appear correct.
Do you know what's going on?

This looks like a really amazing colorscheme, I would love to start using it!

**Comment by sainnhe** [comment]
See FAQ, the comment color looks weird because your terminal emulator doesn't support italics. Use g:edge_disable_italic_comment to disable it.

**Comment by bngldmn** [comment]
Thanks! All fixed! Looks great!
