### ISSUE TITLE
let g:edge_better_performance = 1 cause errors on Windows

### ISSUE THREAD

**Issue by jdhao** [sainnhe/edge#20]
Steps to reproduce. Use the following minimal config:

```vim
set runtimepath+=C:\Users\Administrator\AppData\Local\nvim-data\plugged\edge
let g:edge_enable_italic = 1
let g:edge_better_performance = 1
colorscheme edge
```

Open nvim with `nvim -u minimal.vim`. I am seeing a lot of errors.

Judging from the errors. It seems that edge try to create directory `C:\Users\Administrator\AppData\Local\nvim-data\plugged\edge\colors\edge.vim\after\ftplugin`. In fact it should create directory: `C:\Users\Administrator\AppData\Local\nvim-data\plugged\edge\after\ftplugin`.

**Comment by jdhao** [comment]
The culprit is the following comamnd [here](https://github.com/sainnhe/edge/blob/e40571b69c78f60b6acf0e7b3f1b008b5c72778a/autoload/edge.vim#L206):

```
    return substitute(a:path, '/colors/edge\.vim$', '', '')
```

Since file path on Windows use backslash, the above command can not get the root directory of plugin edge. It still returns the full path to edge.vim: `C:\Users\Administrator\AppData\Local\nvim-data\plugged\edge\colors\edge.vim`. We need to figure out another way to get the root path of edge.

**Comment by sainnhe** [comment]
Thank you for the fix!
