### ISSUE TITLE
Less contrast on DiffText in light mode

### ISSUE THREAD

**Issue by kristijanhusak** [sainnhe/edge#22]
Hi,

what do you think about changing the default "DiffText" color for light mode? Current setup has a bit too big contrast:

![screenshot](https://i.imgur.com/4lbLFy9.png)

I think having a bit Darker blue would do the trick.

**Comment by sainnhe** [comment]
I prefer higher contrast like this, because by doing so we can easily distinguish DiffText from DiffAdded, DiffChanged and DiffDeleted.

If this is not the case for you, welcome to fork this repository ;)

**Comment by kristijanhusak** [comment]
Ok, thanks.
