### ISSUE TITLE
vim-clap support

### ISSUE THREAD

**Issue by iamjesper** [sainnhe/edge#23]
Would you consider adding support for [`vim-clap`](https://github.com/liuchengxu/vim-clap)? 

The author of the plugin has an example theme [here](https://github.com/liuchengxu/vim-clap/blob/master/autoload/clap/themes/material_design_dark.vim) that could be used for reference.

And thanks for the awesome themes. The wide plugin support is really great :)

**Comment by sainnhe** [comment]
Done via ec5eb67.

**Comment by iamjesper** [comment]
Thank you, that was fast! <3
