### ISSUE TITLE
E5113: Error while calling lua chunk: <path> Vim(return):E121: Undefined variable: palette

### ISSUE THREAD

**Issue by rafamadriz** [sainnhe/edge#27]
When setting colorscheme to edge. Neovim gives the following error:
 
```
E5113: Error while calling lua chunk: /home/rafa/.config/nvim/lua/main/colorscheme.lua:21: Vim(return):E121: 
Undefined variable: palette
````
It gives that error and it doesn't set the colorscheme to edge, just fells back to neovim builtin default colorscheme.

I have my config in Lua and this is how I'm setting the colorscheme: `vim.cmd("colorscheme edge")` And it works with all colorschemes I have, except now for edge. Last time I set my colorscheme to edge was all working fine.   

![2021-Apr-28](https://user-images.githubusercontent.com/67771985/116457254-ae4d0580-a852-11eb-827b-8afedd1c19d2.png)

**Comment by sainnhe** [comment]
Closed since I can't reproduce and the user didn't follow the issue template. https://github.com/sainnhe/sonokai/issues/23
