### ISSUE TITLE
Black background

### ISSUE THREAD

**Issue by Skallwar** [sainnhe/edge#43]
Hi,

First of all thanks for this great theme.
I'm having some issue to get a complete dark background on neovim. Usually, setting
both `highlight Normal ctermbg=NONE` and ` highlight nonText ctermbg=NONE` are sufficient to override a them background but it is not the case for edge.

Is there a way to do this directly using via some `edge` specific configuration ?

![image](https://user-images.githubusercontent.com/15075443/147140042-af0df904-336d-4dba-b567-fff7fb2748e6.png)
![image](https://user-images.githubusercontent.com/15075443/147140131-80713045-8fec-4239-8893-c5f38d483237.png)

Archlinux info:
```
$ uname -a
Linux oakfire 5.10.87-1-lts #1 SMP Fri, 17 Dec 2021 10:43:27 +0000 x86_64 GNU/Linux
```

Neovim info:
```
$ nvim --version
NVIM v0.6.0-dev+565-g8cbe100fc
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az50-670

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

init.lua snippet:
```
vim.cmd([[
   set background=dark
   colorscheme edge
   highlight Normal ctermbg=NONE
   highlight nonText ctermbg=NONE
]])
```

**Comment by sainnhe** [comment]
Set ctermbg=NONE doesn't mean a black background, instead it will cause neovim to use your terminal background color.

If you want to use terminal background color, there's a more convenient way, check g:edge_transparent_background in help doc.

---

Btw, this color scheme is designed for true colors, it's recommended to set termguicolors.
