### ISSUE TITLE
Support color for fzf.vim

### ISSUE THREAD

**Issue by HungPham3112** [sainnhe/edge#45]
Before I use edge as default color for gui, I used to dracula theme.
Dracula:
![image](https://user-images.githubusercontent.com/75968004/147821380-515b5065-b37c-4a2e-b4f8-baead2a992af.png)

Edge:
![image](https://user-images.githubusercontent.com/75968004/147821433-fcbb4569-1172-48c8-8575-52b8c8ebd5d7.png)

I can't find out what happen with the preview box, It disappear.

**Comment by sainnhe** [comment]
I don't use fzf and can't reproduce this, please file a new issue and follow the issue template to provide detailed information
