### ISSUE TITLE
Change guibg not work

### ISSUE THREAD

**Issue by rickywu** [sainnhe/edge#48]
### Operating system/version

Windows 10

### GUI client/version

neovim 0.6

### Feature matrix

\ 'bg0':        ['#eeeeec',   '231'],

### Minimal vimrc that can reproduce this bug.

colorscheme edge

### Steps to reproduce this bug using minimal vimrc

change bg0 color and restart neovim

### Expected behavior

shoud use #eeeeec as guibg

### Actual behavior

I changed the light style bg but still use #ffffff as guibg, the file is autoload/edge.vim

    let palette = {
          \ 'black':      ['#dde2e7',   '253'],
          \ 'bg0':        ['#**eeeeec**',   '231'],
          \ 'bg1':        ['#eef1f4',   '255'],
          \ 'bg2':        ['#e8ebf0',   '254'],
          \ 'bg3':        ['#e8ebf0',   '253'],
          \ 'bg4':        ['#dde2e7',   '253'],
          \ 'bg_grey':    ['#bcc5cf',   '246'],
          \ 'bg_red':     ['#ef2929',   '167'],
          \ 'diff_red':   ['#cc0000',   '217'],
          \ 'bg_green':   ['#6b8e23',   '107'],
          \ 'diff_green': ['#4e9a06',   '150'],
          \ 'bg_blue':    ['#3465a4',   '68'],
          \ 'diff_blue':  ['#4169e1',   '153'],
          \ 'bg_purple':  ['#9400d3',   '134'],
          \ 'diff_yellow':['#fcaf3e',   '183'],
          \ 'fg':         ['#2e3436',   '240'],
          \ 'red':        ['#cc0000',   '167'],
          \ 'yellow':     ['#f57900',   '172'],
          \ 'green':      ['#608e23',   '107'],
          \ 'cyan':       ['#87ceeb',   '73'],
          \ 'blue':       ['#204a87',   '68'],
          \ 'purple':     ['#8a2be2',   '134'],
          \ 'grey':       ['#888a85',   '245'],
          \ 'grey_dim':   ['#babdb6',   '249'],
          \ 'none':       ['NONE',      'NONE']
          \ }

**Comment by sainnhe** [comment]
There is no such option in this color scheme, you may need to fork this repository.
