### ISSUE TITLE
g:fzf_colors on light background makes the text invisible in fzf window

### ISSUE THREAD

**Issue by janlazo** [sainnhe/edge#5]
g:fzf_colors is okay in dark background.

Tested with fzf.vim, GFiles command, termguicolors on, light background.

Workaround is to use an autocmd to `unlet g:fzf_colors` after setting the colorscheme.

**Comment by sainnhe** [comment]
I'm unable to reproduce this.

Minimal configuration:

```vim
if has('nvim')
    set runtimepath^=~/.vim runtimepath+=~/.vim/after
    let &packpath = &runtimepath
endif
call plug#begin('~/.cache/vim/plugins')
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'sainnhe/edge', { 'as': 'vim-color-edge' }
call plug#end()

set termguicolors
set background=light

augroup testFzf
    autocmd!
    autocmd ColorScheme * unlet g:fzf_colors
augroup END

colorscheme edge
```

Demo:

![demo](https://user-images.githubusercontent.com/37491630/70848916-41320d80-1eb3-11ea-86f0-6c4c215e86e9.png)

I think this is visible enough, please provide steps to reproduce it.

In addition, why do you want to `unlet g:fzf_colors`? This color scheme is optimized specifically for fzf.

**Comment by janlazo** [comment]
![nvim-qt_nvim-0 5 0_ubuntu](https://user-images.githubusercontent.com/8740057/70850781-284a3d80-1e5c-11ea-816d-9796ca725f8b.png)

Ubunutu 16.04

![gvim_vim-8 1 2380_win10](https://user-images.githubusercontent.com/8740057/70850784-2ed8b500-1e5c-11ea-9d1e-41b7cef25d31.png)

Windows 10 (Edge VM).
I can't replicate the invisible text on the VM. I saw it on my  Windows work machine only so I'll add the screenshot if needed next week.

**Comment by janlazo** [comment]
![nvim-qt_nvim-0 5 0_win10](https://user-images.githubusercontent.com/8740057/70853880-05328480-1e82-11ea-9ab2-a0000ae7b1ac.png)

nvim-qt, nvim 0.5.0, Windows 10 (Edge VM).
I reproduced here.

**Comment by janlazo** [comment]
I'll mitigate the background issue upstream instead.
