### ISSUE TITLE
[Question] Is there any way to change vim colorscheme and status line theme at the same time?

### ISSUE THREAD

**Issue by hungpham3112** [sainnhe/edge#54]
When I try to change the color from default to edge, I have to change 2 places, one is `colorscheme edge` and second is 
```
let g:lightline = {
    \ 'colorscheme': 'edge',
    \}
```

It's quite annoying to me. Thanks in advance for your help.

**Comment by sainnhe** [comment]
This feature has nothing to do with a color scheme, you need to write some scripts.

For reference, I've done this in my [dotfiles](https://github.com/sainnhe/dotfiles/blob/master/.config/nvim/autoload/custom/colorscheme.vim).
