### ISSUE TITLE
Wrong coloring with Treesitter

### ISSUE THREAD

**Issue by gaborvecsei** [sainnhe/edge#58]
### Operating system/version

macOS/Ubuntu

### Terminal emulator/version

iTerm2/Kitty

### $TERM environment variable

xterm-256color

### Feature matrix

NVIM v0.8.0-dev+302-gaf2899aee
Build type: Release
LuaJIT 2.1.0-beta3

### Minimal vimrc that can reproduce this bug.

```vim
call plug#begin('~/.config/nvim/plugged/')

Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'sainnhe/edge'

call plug#end()

lua << EOF
    require'nvim-treesitter.configs'.setup {
    ensure_installed = {'python'},
    sync_install = false,
    ignore_install = {},
    highlight = {
          enable = true, -- `false` will disable the whole extension
          additional_vim_regex_highlighting = false,
    },
}
EOF

if (has('termguicolors'))
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif

" Edge Theme
let g:edge_style = 'neon'
colorscheme edge
```

### Steps to reproduce this bug using minimal vimrc

0. `nvim +PlugClean +PlugInstall`
1. `nvim <any python file>`

### Expected behavior

I should see the same coloring as I can see on the screenshots provided in the `README`.

(With `vim-polygot` it is working fine.)

### Actual behavior

I attached the image how it colors my script:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/18753533/173797222-a0c72265-eb52-4946-8507-1e0d1d7116e5.png">

**Comment by gaborvecsei** [comment]
Truecolor test output:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/18753533/173798499-bf568011-f010-49fe-9c99-322f56d3ca34.png">

**Comment by sainnhe** [comment]
You mean you want white colors?

Simply disable tree-sitter in python.
