### ISSUE TITLE
NvimTree background color is not transparent as before

### ISSUE THREAD

**Issue by thaiducdung255** [sainnhe/edge#68]
### I have done the following steps before reporting this issue:

- [X] I have searched the existing issues
- [X] I have read the FAQ in the help doc

### Operating system/version

manjaro

### Terminal emulator/version

kitty 0.26.5

### $TERM environment variable

xterm-kitty

### Feature matrix

diffview: require("diffview.health").check()
========================================================================
## Checking plugin dependencies
  - OK: plenary installed.
  - OK: nvim-web-devicons installed.

## Checking external dependencies
  - OK: Git found.
  - OK: Git is up-to-date.

gitsigns: require("gitsigns.health").check()
========================================================================
  - OK: git version 2.38.1

hop: require("hop.health").check()
========================================================================
## Ensuring keys are unique
  - OK: Keys are unique

## Checking for deprecated features
  - OK: All good

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.6.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - make           ✓ . ✓ . ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - json           ✓ ✓ ✓ ✓ .
  - rust           ✓ ✓ ✓ ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - dockerfile     ✓ . . . ✓
  - css            ✓ . ✓ ✓ ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - tsx            ✓ ✓ ✓ ✓ ✓
  - typescript     ✓ ✓ ✓ ✓ ✓
  - bash           ✓ ✓ ✓ . ✓
  - cmake          ✓ . ✓ . .
  - yaml           ✓ ✓ ✓ ✓ ✓
  - http           ✓ . . . ✓
  - go             ✓ ✓ ✓ ✓ ✓
  - rasi           ✓ ✓ ✓ ✓ .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3"
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.10.8
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]
  - INFO: Host: /usr/bin/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.9.0

## Node.js provider (optional)
  - INFO: Node.js: v18.6.0
  - INFO: Nvim node.js host: /home/dungtd10/.fnm/node-versions/v18.6.0/installation/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn/pnpm package is installed: 4.10.1

## Perl provider (optional)
  - WARNING: "Neovim::Ext" cpan module is not installed
    - ADVICE:
      - See :help |provider-perl| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.5.2

## Telescope Extension: `hop`
  - INFO: No healthcheck provided

telescope._extensions.repo: require("telescope._extensions.repo.health").check()
========================================================================
  - OK: Will use `bat` to preview non-markdown READMEs
  - OK: Will use `bat` to preview markdown READMEs
  - WARNING: Install `glow` for a better preview of markdown files
  - OK: locate: found `locate`
    mlocate 0.26
    Copyright (C) 2007 Red Hat, Inc. All rights reserved.
    This software is distributed under the GPL v.2.
    
    This program is provided with NO WARRANTY, to the extent permitted by law.
  - INFO: Repos found for `:Telescope repo cached_list`:
    /home/dungtd10/.cache/yay/apache-tools/.git, /home/dungtd10/.cache/yay/electron8-bin/.git...
  - OK: fd: found `fd`
    fd 8.5.2
  - INFO: Repos found for `:Telescope repo list`:
    ...

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/dungtd10/.local/state/nvim/lsp.log
  - INFO: Log size: 1682 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for bash: ABI version 14
  - OK: Loaded parser for cmake: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for dockerfile: ABI version 14
  - OK: Loaded parser for go: ABI version 14
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for http: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for make: ABI version 13
  - OK: Loaded parser for python: ABI version 14
  - OK: Loaded parser for rasi: ABI version 13
  - OK: Loaded parser for rust: ABI version 14
  - OK: Loaded parser for tsx: ABI version 13
  - OK: Loaded parser for typescript: ABI version 14
  - OK: Loaded parser for yaml: ABI version 13

### Minimal vimrc that can reproduce this bug.

vim.g.edge_style                     = 'aura'
vim.g.edge_enable_italic             = 1
vim.g.edge_dim_foreground            = 1
vim.g.edge_disable_italic_comment    = 1
vim.g.edge_better_performance        = 1
vim.g.edge_disable_terminal_colors   = 1
vim.g.edge_menu_selection_background = 'red'

vim.g.edge_colors_override = {
   none       = { 'NONE', 'NONE' },
   black      = { '#202023', '232' }, -- window border bg color
   bg0        = { '#0a0a0a', '235' }, -- bg color
   bg1        = { '#33353f', '235' }, -- status bar > empty bg color
   bg2        = { '#202023', '236' }, -- auto complete window bg color
   bg4        = { '#202023', '236' }, -- status bar > file name bg color
   cyan       = { '#5dbbc1', '100' }, -- ts bracket color
   purple     = { '#d38aea', '100' }, -- ts import color
   bg_grey    = { '#33353f', '100' }, -- lsp auto complete window scrollbar
   bg3        = { '#ec0000', '236' },
   green      = { '#a0c980', '100' },
   bg_green   = { '#a0c980', '100' },
   diff_green = { '#394634', '100' },
   blue       = { '#6cb6eb', '100' },
   bg_blue    = { '#6cb6eb', '100' },
   diff_blue  = { '#354157', '100' },
   -- red         = {},
   -- bg_red      = {},
   -- diff_red    = {},
   -- yellow      = {},
   -- diff_yellow = {},
}

vim.cmd('colorscheme edge')

vim.cmd('hi BufferLineFill guibg=#33353f') -- buffer line empty space

vim.cmd('hi BufferLineBackground guibg=#070707 guifg=#33353f') -- bufferline not visible
vim.cmd('hi BufferLineSeparator guibg=#070707 guifg=#33353f') -- bufferline sep not visible

vim.cmd('hi BufferLineSeparatorSelected guifg=#33353f') -- bufferline sep selected
vim.cmd('hi BufferLineSeparatorVisible guifg=#33353f guibg=#070707') -- bufferline sep selected

vim.cmd('hi BufferLineBufferVisible guibg=#070707 guifg=#57e1ed') -- bufferline visible
vim.cmd('hi BufferLineBufferSelected guifg=#dfe4ed') -- bufferline selected

vim.cmd('hi BufferLineTab guibg=#202023 guifg=#33353f') -- buffer tab index indicator
vim.cmd('hi BufferLineTabSeparator guibg=#33353f guifg=#202023') -- buffer tab index indicator
vim.cmd('hi BufferLineTabSeparatorSelected guibg=#33353f guifg=#0a0a0a') -- buffer tab index indicator
vim.cmd('hi BufferLineTabSelected guifg=#6cb6eb') -- buffer tab index indicator

vim.cmd('hi PmenuSel guibg=#33353f') -- completion menu custom

### Steps to reproduce this bug using minimal vimrc

1.Launch neovim using: nvim
2. Run nvim-tree using: :NvimTreeOpen

### Expected behavior

NvimTree background color is transparent as usual:

![image](https://user-images.githubusercontent.com/43328993/203029069-e9b16ccd-b44c-4280-9eb2-0bf475199290.png)

- I tried using commit: d48ab6039d0f0e4170f921f5e48f4d3e9f0898d and everything works as expected:
![image](https://user-images.githubusercontent.com/43328993/203029501-3431e630-b273-405f-904b-f52eaf9036b0.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/43328993/203029374-8710505a-77a9-410e-bf99-ab089eaf254f.png)

**Comment by sainnhe** [comment]
Should be fixed now.
