### ISSUE TITLE
Color Palette difference between `README.md` and `autoload/edge.vim`

### ISSUE THREAD

**Issue by doprz** [sainnhe/edge#73]
Hi, first of all, I have to say that great job with your color themes/palettes. I've enjoyed using them quite a bit!

I noticed that the colors displayed on the `README.md` and `autoload/edge.vim` differ slightly. Are these changes on purpose?

Edge Dark:
| `README.md` | `autoload/edge.vim` |
| --- | --- |
| "gray_dim": "#535C6A" | "bg_grey": "#828A98" |
| "gray": "#758094" |

I noticed that this issue is persistent throughout all of the displayed themes/variations.

I'm currently working on a project called [dipc](https://github.com/doprz/dipc) - "Convert your favorite images and wallpapers with your favorite color palettes/themes" and I've implemented a couple of your themes.

**Comment by antoineco** [comment]
@Aonodensetsu probably an issue while generating the overview pictures?

**Comment by Aonodensetsu** [comment]
conversion imprecision within Python I'd assume,  not much I can do about it unless some other color conversion library exists

**Comment by Aonodensetsu** [comment]
i made a python program for palette generation, it's in a repository on my profile (prev_gen)

**Comment by doprz** [comment]
Cool!

Do you mind if I create a similar tool as a CLI using Rust so that I may be able to create palette previews for `dipc`?
I would keep it under the same license and credit you as the source of inspiration.

**Comment by Aonodensetsu** [comment]
what I made is easily importable so you shouldn't *need* a rewrite but feel free, maybe rust is more accurate

**Comment by doprz** [comment]
Yes, however, one of my reasons for "rewriting" it is that I've been enjoying writing Rust code and it would also make it easier to use as a utility within `dipc` as it is written in Rust too.

**Comment by Aonodensetsu** [comment]
you'll have to replace the libraries ofc but feel free to look at the source, maybe you'll like some of the data structures

**Comment by Aonodensetsu** [comment]
i found no difference, one color (bg_grey) is omitted because it didn't fit in a nice grid, it's similar to one of the bg colors anyway

**Comment by antoineco** [comment]
@doprz did you double check? If there are differences between the README and Vim palette, could you please list them in a clear format, such as the one below?

-  variant color_name readme_value vim_value

I didn't quite get what the spotted difference was from your original message.

**Comment by Aonodensetsu** [comment]
i checked the code and hex has a perfect conversion to rgb (since it's just a different representation) and the palettes were generated from hex, so there should be no difference

i implemented reversal a few updates ago so you can take a generated image and get the code back (not in full, still figuring out if i can somehow encode the settings in the image, might look into steganography for that) - but it will give back the full list of colors in hex for now

**Comment by antoineco** [comment]
Closing because this seems like a non-issue but feel free to continue to discussion.
