### ISSUE TITLE
Suggestion/Request Helix editor theme.

### ISSUE THREAD

**Issue by zoedsoupe** [sainnhe/edge#75]
Nice work here! I would like to suggest to port this theme also to another editors, for example [helix](https://github.com/helix-editor/helix) which is also a TUI modal editor. Documentation on how to create themes can be found on the [official docs](https://docs.helix-editor.com/themes.html) but also check current implemented themes on their repo: [themes](https://github.com/helix-editor/helix/tree/master/runtime/themes). A good point is that Helix natively supports treesitter!

**Comment by antoineco** [comment]
@zoedsoupe thanks for the suggestion. All ports of this (Neo)vim colorscheme are [community maintained](https://github.com/sainnhe/edge/wiki). Feel free to give it a go and add it to the wiki for others to find.
