### ISSUE TITLE
Secondary colorscheme versions

### ISSUE THREAD

**Issue by ModdedGamers** [sainnhe/edge#9]
Is there any way to use the alternative colorscheme versions(like neon) in kitty or other external programs that aren't vim? Thanks!

**Comment by sainnhe** [comment]
The `aura` and `neon` variants have been added via 7b6e08a

**Comment by metalelf0** [comment]
Sorry for the stupid question, but what are the differences between the versions? I can't seem to find any :(

**Comment by sainnhe** [comment]
@metalelf0 The light variants are almost the same, but the background colors of the dark variants are somewhat different. If you can't distinguish between them, then simply use the default variant :)

**Comment by metalelf0** [comment]
Oh, ok, I didn't check the dark ones - I was using mostly the light one. Thanks :)

**Comment by sainnhe** [comment]
Closed since this has already been fixed.
